
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: pipx install hatch
        - run: hatch run cov
        - name: Coveralls
          uses: coverallsapp/github-action@v2

