
name: test coverage
run-name: test coverage on branch ${{ github.head_ref }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: pipx install hatch
        - run: hatch run cov_xml
        - name: Coveralls
          uses: coverallsapp/github-action@v2

